development:
  adapter: postgresql
  encoding: utf-8
  database: restaurant_development
  username: postgres
  password: postgres

# test:
#   adapter: postgresql
#   encoding: utf-8
#   database: restaurant_test
#   username: postgres
#   password: postgres

# production:
#   adapter: postgresql
#   encoding: utf-8
#   database: restaurant_production
#   username: postgres
#   password: postgres
